# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101S_sSq6jsoxgodHoaCrr_W23qmNXK2g

## 1.IMPORT LIBRARIES
"""

import streamlit as st
import cv2
import numpy as np
import joblib
import os
import time
from skimage.feature import hog

"""## 2.STREAMLIT FRONTEND CONFIGURATION"""

st.set_page_config(page_title="VEHICLE SPEED DETECTOR",layout="wide")
st.title("🚗 Vehicle Speed Estimator & Analytics System")
st.markdown("-----")

# Sidebar setup
st.sidebar.header("🎛️ System Configuration")
SPEED_LIMIT=st.sidebar.slider("Speed Limit (km/h)",min_value=30,max_value=120,value=60)
PPM=st.sidebar.number_input("Pixels Per Meter (PPM Calibration)",min_value=1.0,max_value=50.0,value=10.0)

# Load The Model file
# Load The Model file directly from your GitHub repository workspace
@st.cache_resource
def load_models():
    model_path = "vehicle_svm_detector.joblib"
    scaler_path = "svm_scaler.joblib"
    
    if os.path.exists(model_path) and os.path.exists(scaler_path):
        model = joblib.load(model_path)
        scaler = joblib.load(scaler_path)
        return model, scaler
    return None, None

svm_model, svm_scaler = load_models()

# Fallback check in case the files are named differently in your repo
if svm_model is None:
    st.error("🛑 'vehicle_svm_detector.joblib' & 'svm_scaler.joblib' were not found in the repository root directory.")
    st.info("💡 Double-check that the file names match exactly (lowercase/uppercase) with what you uploaded to GitHub.")
    st.stop()

# Video Upload
uploaded_file=st.file_uploader("Upload Traffic Video File (MP4 ,AVI)",type=["MP4","AVI"])


def stabilize_frame(prev_frame, curr_frame):
    if prev_frame is None:
        return curr_frame
    prev_gray = cv2.cvtColor(prev_frame, cv2.COLOR_BGR2GRAY)
    curr_gray = cv2.cvtColor(curr_frame, cv2.COLOR_BGR2GRAY)

    #to find vibration points
    pts=cv2.goodFeaturesToTrack(prev_gray,maxCorners=100,qualityLevel=0.01,minDistance=30)
    if pts is None:
        return curr_frame

    next_pts,status,_=cv2.calcOpticalFlowPyrLK(prev_gray,curr_gray,pts,None)
    idx=np.where(status==1)[0]

    if len(idx) > 10:
        # இரண்டு ஃபிரேம்களுக்கும் இடையே உள்ள நகர்வு மேட்ரிக்ஸைக் கணக்கிடுதல்
        M,_=cv2.estimateAffinePartial2D(pts[idx],next_pts[idx])
        if M is not None:
            # அதிர்வைச் சீரமைத்து ஃபிரேமைத் திருப்புதல்
            stabilized=cv2.warpAffine(curr_frame,M,(curr_frame.shape[1],curr_frame.shape[2]),flags=cv2.WARP_INVERSE_MAP)
            return stabilized
    return curr_frame


def classify_vehicle(cropped_img):
    if cropped_img is None or cropped_img.size == 0:
        return None

    #resize to the model size (64x64)
    resized=cv2.resize(cropped_img,(64,64))
    gray=cv2.cvtColor(resized,cv2.COLOR_BGR2GRAY)
    #hog extraction
    hog_feat=hog(gray,orientations=9,pixels_per_cell=(8,8),cells_per_block=(2,2),visualize=False)

    #transform the input data using scaler
    scaled_feat=svm_scaler.transform([hog_feat])
    prediction=svm_model.predict(scaled_feat)[0]
    return prediction


class CentroidTracker:
    def __init__(self):
        self.next_id=1
        self.objects={}  # ID -> current_centroid
        self.previous_objects={}  # ID -> previous_centroid
        self.speeds={}  # ID -> calculated_speed
        self.classes={}  # ID -> vehicle_class

    def update(self,rects,frame,fps):
        current_rect_centroids=[]
        for (x,y,w,h) in rects:
            cx=int(x+w/2)
            cy=int(y+h/2)
            current_rect_centroids.append((cx,cy,x,y,w,h))

        new_objects={}
        for (cx,cy,x,y,w,h) in current_rect_centroids:
            #Euclidean Distance Matching
            matched_id=None
            min_dist=50

            for obj_id,old_cx_cy in self.objects.items():
                dist=np.hypot(cx - old_cx_cy[0],cy - old_cx_cy[1])
                if dist < min_dist:
                    min_dist=dist
                    matched_id=obj_id

            if matched_id is not None:
                new_objects[matched_id]=(cx,cy)
                self.previous_objects[matched_id]=self.objects[matched_id]

                #SPEED ESTIMATION MATH
                prev_cx, prev_cy=self.previous_objects[matched_id]
                pixel_dist=np.hypot(cx-prev_cx,cy-prev_cy)

                # convert pixels into meter
                meters=pixel_dist/PPM
                seconds=1.0/fps
                speed_mps=meters/seconds
                speed_kmh=int(speed_mps*3.6)

                #  (
                if matched_id in self.speeds:
                    self.speeds[matched_id]=int(self.speeds[matched_id]*0.7+speed_kmh*0.3)
                else:
                    self.speeds[matched_id]=speed_kmh
            else:
                # Identify the new vehicle,and calculate using svm
                cropped =frame[y:y+h,x:x+w]
                v_class=classify_vehicle(cropped)

                if v_class is not None:
                    new_objects[self.next_id]=(cx,cy)
                    self.classes[self.next_id]=v_class
                    self.next_id+=1

        self.objects=new_objects
        return self.objects


if uploaded_file is not None:
    #save the video temporarily
    with open("temp_video.mp4","wb") as f:
        f.write(uploaded_file.read())

    cap=cv2.VideoCapture("temp_video.mp4")
    fps=cap.get(cv2.CAP_PROP_FPS) if cap.get(cv2.CAP_PROP_FPS)>0 else 30

    #backround subraction for object detection
    object_detector=cv2.createBackgroundSubtractorMOG2(history=100,varThreshold=40)
    tracker=CentroidTracker()

    # UI Layout
    col1,col2=st.columns([2,1])
    with col1:
        st.subheader("🎥 Real-time Video Analysis")
        video_placeholder=st.empty()
    with col2:
        st.subheader("💥 Speed Limit Violations Log (Business Optimization)")
        log_placeholder=st.empty()

    violation_log=[]
    prev_frame=None

    while cap.isOpened():
        ret,frame=cap.read()
        if not ret:
            break

        #Image Stabilization
        stabilized=stabilize_frame(prev_frame, frame)
        prev_frame=stabilized.copy()

        #Object Detection(Foreground Masking)
        mask=aobject_detector.apply(stabilized)
        _,mask=cv2.threshold(mask,254,255,cv2.THRESH_BINARY)
        contours, _=cv2.findContours(mask,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)

        rects=[]
        for cnt in contours:
            area=cv2.contourArea(cnt)
            if area > 400: 
                x,y,w,h=cv2.boundingRect(cnt)
                rects.append((x,y,w,h))

        # 3. Tracker Update
        tracked_objs=tracker.update(rects,stabilized,fps)

        # 6. OVERLAY RESULTS & UI DISPLAY
        for obj_id,(cx,cy) in tracked_objs.items():
            v_class=tracker.classes.get(obj_id,"Detecting...")
            speed=tracker.speeds.get(obj_id, 0)

            #draw the bounding boxes changes red
            for (x,y,w,h) in rects:
                if abs(cx-(x+w/2))<30 and abs(cy-(y+h/2)) < 30:
                    #if velocity exceeds
                    color=(0,0,255) if speed > SPEED_LIMIT else (0,255,0)
                    cv2.rectangle(stabilized,(x,y),(x+w,y+h),color,2)

                    #Class & Speed Overlay
                    label = f"ID:{obj_id} {v_class} | {speed} km/h"
                    cv2.putText(stabilized, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)

                   # 7. BUSINESS-ORIENTED OPTIMIZATION (Violation Logging)
                    if speed > SPEED_LIMIT:
                        log_entry = {"Vehicle ID": obj_id, "Type": v_class, "Speed": f"{speed} km/h", "Status": "🔥 OVER SPEED"}
                        if log_entry not in violation_log:
                            violation_log.append(log_entry)
                            #Data Science View
                            with col2:
                                log_placeholder.dataframe(violation_log, use_container_width=True)

        # show streamlit frames
        frame_rgb=cv2.cvtColor(stabilized,cv2.COLOR_BGR2RGB)
        video_placeholder.image(frame_rgb,channels="RGB",use_container_width=True)


        time.sleep(1/fps)

    cap.release()
    st.success("🎉 Video Speed Prediction Completed! ✨")
